-- ---------------------------------------------------
-- ---------------------------------------------------
-- Algoritmos de los Vistas
-- Sólidos Y Lodos Nacionales SLN <info@sln-ec.com> http://sln-ec.com
-- Autor Eduardo Villota <@eduardouio> <eduardouio@hotmail.com>
-- 
-- En este fichero se encuentran los algoritmos de las vistas mas utiles
-- las mismas que ayudan a resolver cosultas complejas de manera facil
-- las vistas nos permiten tener un facil acceso a la informacion de la
-- base de datos ya sea de una tabla o de varias
--
-- Indice de Vistas
--
-- 1.- v_inv_entrada
-- 2.- v_inv_salida
-- 3.- 
-- 4.-
-- 5.-
-- 6.-
-- 7.-
-- 8.-
-- 9.-
-- ---------------------------------------------------
-- ---------------------------------------------------

  